name: plansy_flutter_app
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  smooth_star_rating: ^1.0.4
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.2
  cloud_firestore: ^1.0.2
  modal_progress_hud: ^0.1.3
  provider: ^5.0.0
  icon_shadow: ^1.0.1
  animations: ^2.0.0
  google_maps_flutter: ^2.0.6
  share: ^0.6.5+4
  screenshot: ^0.2.0
  timeline_tile: ^2.0.0
  intl: ^0.17.0
  mask_text_input_formatter: ^2.0.0
  csc_picker: ^0.2.5
  http: ^0.13.3
  country_currency_pickers: ^2.0.0
  readmore: ^2.1.0
  flutter_fluid_slider: ^1.0.2
  geocoder: ^0.2.1
  geolocator: ^7.4.0
  shared_preferences: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
  - family: RocknRollOne
    fonts:
      - asset:  fonts/RocknRollOne-Regular.ttf
